spring.application.name=average-weather
server.port=${PORT:8080}

weather.cache.ttl-minutes=5
weather.provider.connect-timeout-seconds=2
weather.provider.read-timeout-seconds=3
weather.provider.future-timeout-seconds=3

weather.openweathermap.api-key=${OWM_API_KEY:}
weather.weatherapi.api-key=${WEATHERAPI_KEY:}

springdoc.swagger-ui.path=/swagger-ui.html
